/**
 * StarCraft Ghost (Release) - Recompiled Game Entry Point
 *
 * This is the Windows executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       StarCraft Ghost (Release)
 *   Title ID:    0x00000002
 *   Base addr:   0x00010000
 *   Entry point: 0x001B3FBB
 *   Code size:   ~??? KB (.text)
 *   Sections:    ?? (list them)
 *   Kernel imports: ??
 */

#include <windows.h>
#include <dbghelp.h>
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <errno.h>
#include <io.h>
#include <share.h>
#include "game_paths.h"

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>
#include "ohci.h"
#include "xinput_xbox.h"
#include "apu.h"
#include "apu_debug.h"
#include "recomp_icall_feedback.h"

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. The
 * host side then writes g_esp somewhere the generated code never reads, so the
 * guest starts with every register at zero and faults immediately, having
 * apparently ignored the setup that visibly ran. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
extern RECOMP_TLS uint32_t g_fs_base;
/* x87 and SSE state. Global for the same reason the volatile GPRs are: one
 * guest routine can lift to several C functions, so a value written in one
 * body is read in the next. Defined in xbox_memory_layout.c like the rest of
 * the register file. */
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_TITLE         "StarCraft Ghost (Release)"
#define YOUR_GAME_ENTRY_POINT   0x001B3FBB  /* XBE entry point VA */
/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);
static void redirect_diagnostics(void);

/* Recompiled entry point (generated by recomp pipeline) */
extern void xbe_entry_point(void);

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
/* Name the guest function a fault happened in, and recover the call chain.
 *
 * Recompiled code faults as ordinary native code, so the exception record
 * carries a host RIP and nothing else -- there is no guest program counter to
 * report, and the host address changes every build. Two things recover the
 * guest view:
 *
 *   - every generated function is a real symbol in the image (sub_005A03C0
 *     and so on), so the linker's PDB already maps host address back to guest
 *     function. dbghelp turns an anonymous RIP into that name.
 *
 *   - every lifted call pushes its guest return address onto the guest stack
 *     before jumping, so the stack still holds the chain. Scanning up from esp
 *     for values inside the code sections recovers it.
 *
 * ponytail: the stack scan is a scan, not a frame walk -- these are FPO frames
 * with no reliable ebp chain, so there is nothing to walk. It over-reports,
 * since addresses from returned-from calls linger below esp, but naming the
 * guest function is the whole question at a fault.
 *
 * Requires linking dbghelp and keeping the .pdb beside the .exe.
 */
static void print_guest_context(void *rip)
{
    /* SYMBOL_INFO is variable-length: the name is written past the struct, so
     * it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    AcquireSRWLockExclusive(&g_xbox_debug_symbols_lock);
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n",
                sym->Name, (unsigned long long)disp);
    ReleaseSRWLockExclusive(&g_xbox_debug_symbols_lock);

    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (return addresses, innermost first):\n");
        for (i = 0; i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
        /* When the frame is gone, say so, and fall back on what is left.
         *
         * A fault inside a block copy leaves no return address in range: the
         * copy is a host memmove and its caller's frame is further up than
         * this reaches. Worse, a copy that ran past its buffer overwrites the
         * stack itself, so the list comes out empty exactly when it is most
         * needed -- and an empty list under a promising heading reads like
         * "nothing to see" rather than "the evidence is destroyed". */
        if (!shown)
            fprintf(stderr, "    (no return addresses in range)\n");

        /* Everything below only pays for itself when the scan came back
         * empty. A crash where the chain was recovered already says what
         * happened, and burying that under another twenty lines makes the
         * common report worse to read. */
        if (!shown) {
            uint32_t k;

            /* The indirect-call history, which the stack cannot overwrite.
             * recomp_manual.c prints this too, but only from
             * recomp_icall_fail_log -- a page fault inside a block copy
             * never reaches that path, and this is the same information by
             * the route the fault actually took.
             *
             * Declared here rather than included: main.c does not pull in
             * recomp_types.h, and recomp_manual.c spells it the same way. */
            extern volatile uint32_t g_icall_trace[16];
            extern volatile uint32_t g_icall_trace_idx;

            fprintf(stderr, "  recent ICALL targets:");
            for (k = 0; k < 16; k++)
                fprintf(stderr, " %08X",
                        g_icall_trace[(g_icall_trace_idx + k) & 15]);
            fprintf(stderr, "\n");

            /* The frame unfiltered. The pointers and lengths handed to
             * whatever faulted live here and look nothing like code, so the
             * filter above drops exactly what is wanted. On the crash this
             * was written for, one of these words was the end of the mapped
             * RAM mirror -- which is what identified the fault as a copy
             * running off its buffer rather than a stray pointer. */
            for (i = 0; i < 20; i++)
                fprintf(stderr, "    raw[esp+%-4d] 0x%08X\n", i * 4, sp[i]);
        }
    }
}

/* The emulated APU.
 *
 * Two entry points that had no callers anywhere in the tree. apu_mmio_hook.c
 * documents apu_hook_handle_mmio as "called from VEH in main.c" and no main.c
 * called it; apu_decode_and_handle's first line is `if (!g_apu_state) return
 * false` and nothing assigned g_apu_state. So with RECOMP_AC97_READY set the
 * APU's registers were unmapped to be trapped, and every trap was then
 * declined and surfaced as an access violation on the first register
 * DirectSound touched.
 */
extern MCPXAPUState *g_apu_state;
extern bool apu_hook_handle_mmio(PCONTEXT ctx, uintptr_t fault_addr,
                                 uint32_t fault_xbox_va, int is_write);

/* Match the modeled main/VP MMIO span in MemoryLayoutInit. GP/EP scratch
 * memory and AC'97 remain mapped for bulk copies and codec status. */
#define APU_TRAP_BASE 0xFE800000u
#define APU_TRAP_END  0xFE830000u

static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        /* APU registers -> the emulated APU.
         *
         * The other half of RECOMP_AC97_READY: reporting the codec ready is
         * what lets DirectSoundCreate past its first gate, and from there it
         * drives the APU directly, so the registers have to fault to be seen.
         * "Handled" means the access was decoded and the instruction stepped
         * over, so execution resumes instead of unwinding. */
        {
            uint32_t xbox_va =
                (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);

            if (xbox_OhciOwnsAddress(xbox_va)
                    && xbox_OhciHandleMmio(ep->ContextRecord, xbox_va)) {
                return EXCEPTION_CONTINUE_EXECUTION;
            }

            if (xbox_va >= APU_TRAP_BASE && xbox_va < APU_TRAP_END
                    && apu_hook_handle_mmio(
                           ep->ContextRecord, fault_addr, xbox_va,
                           ep->ExceptionRecord->ExceptionInformation[0]
                               ? 1 : 0)) {
                return EXCEPTION_CONTINUE_EXECUTION;
            }
        }

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));
        fprintf(stderr, "  guest FS base: 0x%08X", g_fs_base);
        if (g_fs_base >= 0x1000 && g_fs_base < 0x04000000)
            fprintf(stderr, " fs:[4]=0x%08X",
                    *(const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_fs_base + 4));
        fprintf(stderr, "\n");
        print_guest_context((void *)ep->ContextRecord->Rip);

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

/* ── WinMain ───────────────────────────────────────────────── */

int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;

    redirect_diagnostics();
    _putenv_s("RECOMP_WINDOW_TITLE", YOUR_GAME_TITLE);
    if (!getenv("RECOMP_APU_DIAG") &&
        _putenv_s("RECOMP_APU_DIAG", "0") != 0) {
        fprintf(stderr, "[BOOT] failed to configure audio diagnostics default\n");
        return 1;
    }
    fprintf(stderr, "[BOOT] audio diagnostics %s (RECOMP_APU_DIAG=%s)\n",
            mcpx_apu_diagnostics_enabled() ? "enabled" : "disabled",
            getenv("RECOMP_APU_DIAG"));
    if (!getenv("RECOMP_AC97_READY"))
        _putenv_s("RECOMP_AC97_READY", "1");
    if (!getenv("RECOMP_DSP_ACK") && !getenv("RECOMP_APU_DSP_ACK")) {
        if (_putenv_s("RECOMP_APU_DSP_ACK", "gp:0x810") != 0) {
            fprintf(stderr, "[BOOT] failed to configure DSP passthrough mailbox\n");
            return 1;
        }
    }
    if (!getenv("RECOMP_NV2A_STREAM_COALESCE") &&
        _putenv_s("RECOMP_NV2A_STREAM_COALESCE", "1") != 0) {
        fprintf(stderr, "[BOOT] failed to configure stream coalescing default\n");
        return 1;
    }
    {
        static const char *const rendering_options[] = {
            "RECOMP_NV2A_GPU_RESIDENT",
            "RECOMP_NV2A_GPU_RESIDENT_IDLE",
            "RECOMP_NV2A_GPU_ASYNC_IDLE",
            "RECOMP_NV2A_STREAM_COALESCE"
        };
        for (size_t i = 0; i < sizeof(rendering_options) / sizeof(rendering_options[0]); i++) {
            const char *value = getenv(rendering_options[i]);
            BOOL enabled = value ? *value && strcmp(value, "0") != 0 :
                           strcmp(rendering_options[i], "RECOMP_NV2A_GPU_ASYNC_IDLE") == 0;
            fprintf(stderr, "[BOOT] rendering option %s=%s (%s)\n",
                    rendering_options[i], value ? value : "<unset>",
                    enabled ? "enabled" : "disabled");
        }
    }
    if (!getenv("RECOMP_USB"))
        _putenv_s("RECOMP_USB", "1");
    if (!getenv("RECOMP_USB_NDP"))
        _putenv_s("RECOMP_USB_NDP", "2");
    {
        static const struct { const char *name, *value; } input_defaults[] = {
            {"RECOMP_XINPUT_SLOT", "auto"},
            {"RECOMP_KEYBOARD", "0"},
            {"RECOMP_INPUT_THRESHOLD", "30"},
            {"RECOMP_INPUT_DEADZONE_LEFT", "0"},
            {"RECOMP_INPUT_DEADZONE_RIGHT", "0"},
            {"RECOMP_INPUT_AXES", "0"}
        };
        for (size_t i = 0; i < sizeof(input_defaults) / sizeof(input_defaults[0]); i++) {
            if (!getenv(input_defaults[i].name) &&
                _putenv_s(input_defaults[i].name, input_defaults[i].value) != 0) {
                fprintf(stderr, "[BOOT] failed to set %s\n", input_defaults[i].name);
                return 1;
            }
        }
    }
    if (!getenv("RECOMP_PB_EXEC"))
        _putenv_s("RECOMP_PB_EXEC", "1");
    if (!getenv("RECOMP_NV2A_NATIVE_FENCES")
            && _putenv_s("RECOMP_NV2A_NATIVE_FENCES", "1") != 0) {
        fprintf(stderr, "[BOOT] Cannot configure native GPU command completion\n");
        return EXIT_FAILURE;
    }
    if (xbox_Nv2aNativeFencesEnabled()
            && !getenv("RECOMP_VBLANK") && _putenv_s("RECOMP_VBLANK", "1") != 0) {
        fprintf(stderr, "[BOOT] Cannot enable native GPU vblank delivery\n");
        return EXIT_FAILURE;
    }
    /* Unbuffered output for immediate visibility during debugging */
    setvbuf(stdout, NULL, _IONBF, 0);
    setvbuf(stderr, NULL, _IONBF, 0);

    printf("=== %s - Static Recompilation ===\n", YOUR_GAME_TITLE);
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    /* Load symbols up front rather than from inside the handler: at fault
     * time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler prints no name. */
    AcquireSRWLockExclusive(&g_xbox_debug_symbols_lock);
    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME | SYMOPT_LOAD_LINES);
    {
        BOOL initialized = SymInitialize(GetCurrentProcess(), NULL, TRUE);
        DWORD error = initialized ? 0 : GetLastError();
        ReleaseSRWLockExclusive(&g_xbox_debug_symbols_lock);
        if (!initialized)
            fprintf(stderr, "[BOOT] Cannot initialize diagnostic symbols: %lu\n", error);
    }
    AddVectoredExceptionHandler(1, veh_handler);

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        printf("xbe path: %s\n",YOUR_GAME_XBE_PATH);
        printf("game dir: %s\n",YOUR_GAME_DIR);
        MessageBoxA(NULL, "Failed to load default.xbe.\n"
                    "Place the game files in the 'game' subdirectory.",
                    "Recomp", MB_ICONERROR);
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        MessageBoxA(NULL, "Failed to initialize Xbox memory layout.\n"
                    "The required virtual address range may be unavailable.",
                    "Recomp", MB_ICONERROR);
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Bring up the emulated APU.
     *
     * Gated on the same variable that unmaps its registers, because the two
     * halves are useless apart: a trap with no model declines every access,
     * and a model nothing traps into never sees a register. The APU walks
     * Xbox physical RAM to find voice tables and sample buffers. The mapper
     * resolves both contiguous allocations and ordinary-RAM payloads. */
    if (getenv("RECOMP_AC97_READY")) {
        g_apu_state = mcpx_apu_init_standalone_mapped(
            (uint8_t *)((uintptr_t)g_xbox_mem_offset + XBOX_CONTIG_BASE),
            xbox_DmaPhysicalPointer);
        fprintf(stderr, "[BOOT] emulated APU %s\n",
                g_apu_state ? "up" : "FAILED to initialise");
    }

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        xbox_path_init(YOUR_GAME_DIR, NULL);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();
    xbox_InputInit();
    xbox_OhciInit();
    if (xbox_Nv2aNativeFencesEnabled()) {
        if (xbox_Nv2aSoftwareMethodHandler(0x002C99B0u, 0x002D3D78u) < 0)
            return EXIT_FAILURE;
    } else {
        xbox_Nv2aMirrorFence(0x002D2148u, 0x2Cu, 0x30u);
        xbox_Nv2aFrameCounter(0x002D2148u, 0x1DE8u);
    }

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over the
     * whole function table -- roughly log2(n) branches on *every*
     * indirect call, which for a 45,000-function C++ title is about 16
     * every time the game goes through a vtable. Half-Life 2 spent most
     * of its static initialisation inside recomp_lookup for exactly this
     * reason, and it read as a hang.
     *
     * Optional by design: if the allocation fails the search still works,
     * so a failure is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    /* Arm the hang watchdog. Does nothing unless RECOMP_WATCHDOG_SECS is set,
     * and must be called from this thread -- the guest registers it samples are
     * thread-local, so it has to be handed the copies belonging to the thread
     * that runs guest code.
     *
     * Not optional boilerplate: without this call RECOMP_WATCHDOG_SECS is
     * silently inert, and the one diagnostic that tells a hang from slowness
     * does nothing while appearing to be set. */
    xbox_WatchdogStart();

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

static BOOL redirect_diagnostic_stream(FILE *destination, const char *path)
{
    FILE *source = _fsopen(path, "w", _SH_DENYWR);
    if (!source) {
        fprintf(stderr, "[BOOT] could not open diagnostic log '%s' (errno %d)\n",
                path, errno);
        return FALSE;
    }
    if (_fileno(destination) < 0) {
        FILE *initialized;
        if (freopen_s(&initialized, "NUL", "w", destination) != 0) {
            fclose(source);
            OutputDebugStringA("[BOOT] could not initialize diagnostic stream\n");
            return FALSE;
        }
    }
    if (fflush(destination) != 0 ||
        _dup2(_fileno(source), _fileno(destination)) != 0) {
        int error = errno;
        fclose(source);
        fprintf(stderr, "[BOOT] could not redirect diagnostic log '%s' (errno %d)\n",
                path, error);
        return FALSE;
    }
    if (fclose(source) != 0) {
        fprintf(stderr, "[BOOT] could not close duplicate log stream '%s' (errno %d)\n",
                path, errno);
        return FALSE;
    }
    return TRUE;
}

static void redirect_diagnostics(void)
{
    char log_path[MAX_PATH];
    char error_path[MAX_PATH];
    DWORD path_len = GetModuleFileNameA(NULL, log_path, MAX_PATH);
    char *last_slash;

    if (path_len == 0 || path_len >= MAX_PATH)
        return;

    last_slash = strrchr(log_path, '\\');
    if (!last_slash)
        return;

    last_slash[1] = '\0';
    if (strcpy_s(error_path, sizeof(error_path), log_path) != 0 ||
        strcat_s(error_path, sizeof(error_path), "Ghost-errors.log") != 0)
        return;
    if (strcat_s(log_path, sizeof(log_path), "Ghost-run.log") != 0)
        return;

    if (!redirect_diagnostic_stream(stdout, log_path))
        return;
    if (!redirect_diagnostic_stream(stderr, error_path))
        fprintf(stdout, "[BOOT] could not redirect stderr\n");
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
}
